In [13]:
from __future__ import print_function, division
from builtins import range, input
# Note: you may need to update your version of future
# sudo pip install -U future

from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt

import keras.backend as K
if len(K.tensorflow_backend._get_available_gpus()) > 0:
    from keras.layers import CuDNNLSTM as LSTM
    from keras.layers import CuDNNGRU as GRU


T = 8
D = 2
M = 3


X = np.random.randn(1, T, D)


In [14]:


def lstm_Returnstate_true():
    input_ = Input(shape=(T, D))
    rnn = LSTM(M, return_state=True)
    x = rnn(input_)

    model = Model(inputs=input_, outputs=x)
    o, h, c = model.predict(X)
    print("o:", o)
    print("h:", h)
    print("c:", c)


def lstm_Returnstate_AND_returnsequence_true():
    input_ = Input(shape=(T, D))
    rnn = LSTM(M, return_state=True, return_sequences=True)
    # rnn = GRU(M, return_state=True)
    x = rnn(input_)

    model = Model(inputs=input_, outputs=x)
    o, h, c = model.predict(X)
    print("o:", o)
    print("h:", h)
    print("c:", c)


def gru_Returnstate_true():
    input_ = Input(shape=(T, D))
    rnn = GRU(M, return_state=True)
    x = rnn(input_)

    model = Model(inputs=input_, outputs=x)
    o, h = model.predict(X)
    print("o:", o)
    print("h:", h)


def gru_Returnstate_AND_returnsequence_true():
    input_ = Input(shape=(T, D))
    rnn = GRU(M, return_state=True, return_sequences=True)
    x = rnn(input_)

    model = Model(inputs=input_, outputs=x)
    o, h = model.predict(X)
    print("o:", o)
    print("h:", h)





In [15]:
print(X)

[[[ 0.59770203 -1.77543792]
  [ 1.57415438  0.06258254]
  [-0.41013369 -0.65110409]
  [-0.6387672   0.71499926]
  [-1.2551291  -0.18229779]
  [ 0.16753876 -0.07189795]
  [-0.84034669 -0.58607109]
  [ 0.52870897 -0.04132431]]]


In [16]:
print("lstm_Returnstate_true:\n")
lstm_Returnstate_true()



lstm_Returnstate_true:

o: [[0.10098546 0.07345855 0.13779718]]
h: [[0.10098546 0.07345855 0.13779718]]
c: [[0.23691705 0.16269636 0.27071425]]


### (sequence off => only last output)output (o) = h() (hidden weight)

In [17]:
print("lstm_Returnstate_AND_returnsequence_true:\n")
lstm_Returnstate_AND_returnsequence_true()


lstm_Returnstate_AND_returnsequence_true:

o: [[[-0.07742085  0.08336933 -0.08741067]
  [-0.08392014  0.22832906 -0.11696269]
  [-0.0882296   0.08592086 -0.14338201]
  [-0.04461702 -0.03219777 -0.02296619]
  [-0.01677374 -0.0765813   0.09561656]
  [-0.01820315 -0.05259386  0.05045644]
  [-0.01193126 -0.0396757   0.12601651]
  [-0.02017559  0.00416929  0.03921372]]]
h: [[-0.02017559  0.00416929  0.03921372]]
c: [[-0.04523549  0.00753654  0.08610378]]


### (sequence on => all output) output (o) = h() (hidden weight)(still)
here 8 output bcoz we have 8 rows of data with two fetures

In [18]:
print("gru_Returnstate_true:\n")
gru_Returnstate_true()


gru_Returnstate_true:

o: [[ 0.1031701  -0.07571063 -0.06093329]]
h: [[ 0.1031701  -0.07571063 -0.06093329]]


### (sequence off => only last output)output (o) = h() (hidden weight)

In [19]:
print("gru_Returnstate_AND_returnsequence_true:\n")
gru_Returnstate_AND_returnsequence_true()

gru_Returnstate_AND_returnsequence_true:

o: [[[ 0.41126525  0.46204838 -0.15682572]
  [ 0.66549796  0.05200069 -0.18274572]
  [ 0.39732218  0.29752    -0.06487527]
  [ 0.01592791  0.0638899   0.10468091]
  [-0.2184583   0.28934878  0.1566674 ]
  [ 0.00994719  0.09565081  0.01362375]
  [-0.13003094  0.36673814  0.03617081]
  [ 0.18083726  0.07897285 -0.06370836]]]
h: [[ 0.18083726  0.07897285 -0.06370836]]


### (sequence off => only last output)output (o) = h() (hidden weight)

# Observation
* h(hidden state) and c(cell state) are final hidden state of LSTM
* i.e at last time stamp output = hidden state

* h(hidden state) and c(cell state) are final hidden state of gru
* i.e at last time stamp output = hidden state